# Generated by Django 4.2.18 on 2025-01-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Demo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("middle_name", models.CharField(blank=True, max_length=30, null=True)),
                ("last_name", models.CharField(max_length=30)),
                ("suffix", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "demo",
            },
        ),
    ]
