# Generated by Django 4.2.18 on 2025-01-31 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperOrg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("flag", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="demo",
            name="super_org",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="demo.superorg",
            ),
            preserve_default=False,
        ),
    ]
