# Generated by Django 4.2.18 on 2025-01-31 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_demo_name_formats"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="demo",
            table="my_demo",
        ),
        migrations.AlterModelTable(
            name="superorg",
            table="super_org",
        ),
    ]
