# Generated by Django 4.2.18 on 2025-01-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0006_update_trigger"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demo",
            name="name_formats",
        ),
        migrations.AddField(
            model_name="demo",
            name="display_first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="demo",
            name="display_full_name_first_name_first",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="demo",
            name="display_full_name_last_name_first",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="demo",
            name="display_last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
